name: Seichi915HubCore
version: 1.0.0
main: net.seichi915.seichi915hubcore.Seichi915HubCore
api-version: "1.13"
load: POSTWORLD
authors: [stouma915]
description: "seichi915Hub コアプラグイン"
website: https://www.seichi915.net
depend:
  - Multiverse-Core
commands:
  athletic:
    description: Teleport to athletic world
    usage: /athletic
    permission: seichi915hubcore.command.athletic
    permission-message: "§c権限が不足しています。"
permissions:
  seichi915hubcore.*:
    description: Grant all permissions of seichi915HubCore
    children:
      seichi915hubcore.command.*: true
  seichi915hubcore.command.*:
    description: Grant all command permissions of seichi915HubCore
    children:
      seichi915hubcore.command.athletic: true
  seichi915hubcore.command.athletic:
    description: Permission to use /athletic
    default: true
