name: Seichi915HubCore
version: 1.0.0
main: net.seichi915.seichi915hubcore.Seichi915HubCore
api-version: "1.13"
load: POSTWORLD
authors: [stouma915]
description: "seichi915Hub コアプラグイン"
website: https://www.seichi915.net
commands: {}
permissions:
  seichi915hubcore.*:
    description: Grant all permissions of seichi915HubCore
    children:
      seichi915hubcore.command.*: true
  seichi915hubcore.command.*:
    description: Grant all command permissions of seichi915HubCore
    children: {}
