name: Seichi915HubCore
version: 1.0.2
main: net.seichi915.seichi915hubcore.Seichi915HubCore
api-version: "1.13"
load: POSTWORLD
authors: [stouma915]
description: "seichi915Hub コアプラグイン"
website: https://www.seichi915.net
depend:
  - Multiverse-Core
commands:
  pvp:
    description: Teleport to PvP world
    usage: /pvp
    permission: seichi915hubcore.command.pvp
    permission-message: "§c権限が不足しています。"
  admins:
    description: Teleport to administrator introduction world
    usage: /admins
    permission: seichi915hubcore.command.admins
    permission-message: "§c権限が不足しています。"
  main:
    description: Teleport to main world
    usage: /main
    permission: seichi915hubcore.command.main
    permission-message: "§c権限が不足しています。"
  menu:
    description: Open menu
    usage: /menu
    permission: seichi915hubcore.command.menu
    permission-message: "§c権限が不足しています。"
  spawn:
    description: Teleport to spawn point
    usage: /spawn
    permission: seichi915hubcore.command.spawn
    permission-message: "§c権限が不足しています。"
permissions:
  seichi915hubcore.*:
    description: Grant all permissions of seichi915HubCore
    children:
      seichi915hubcore.command.*: true
  seichi915hubcore.command.*:
    description: Grant all command permissions of seichi915HubCore
    children:
      seichi915hubcore.command.pvp: true
      seichi915hubcore.command.admins: true
      seichi915hubcore.command.main: true
      seichi915hubcore.command.menu: true
      seichi915hubcore.command.spawn: true
  seichi915hubcore.command.pvp:
    description: Permission to use /pvp
    default: true
  seichi915hubcore.command.admins:
    description: Permission to use /admins
    default: true
  seichi915hubcore.command.main:
    description: Permission to use /main
    default: true
  seichi915hubcore.command.menu:
    description: Permission to use /menu
    default: true
  seichi915hubcore.command.spawn:
    description: Permission to use /spawn
    default: true
